---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhu.
--- DateTime: 2026/8/5 19:02
---

RichText = RichText or {}

function RichText.EscapeText(Text)
    Text = tostring(Text or "")
    Text = string.gsub(Text, "&", "&amp;")
    Text = string.gsub(Text, "<", "&lt;")
    Text = string.gsub(Text, ">", "&gt;")
    return Text
end

--- @param Text string
--- @param Style table
function RichText.Font(Text, Style)
    Style = Style or {}

    local AttrList = {}

    if Style.src then
        table.insert(AttrList, string.format('src="%s"', Style.src))
    end

    if Style.size then
        table.insert(AttrList, string.format('size="%s"', tostring(Style.size)))
    end

    if Style.color then
        table.insert(AttrList, string.format('color="%s"', Style.color))
    end

    if Style.use_shadow then
        table.insert(AttrList, string.format('use_shadow="%s"', tostring(Style.use_shadow)))
    end

    if Style.shadow_color then
        table.insert(AttrList, string.format('shadow_color="%s"', Style.shadow_color))
    end

    if Style.shadow_offset then
        table.insert(AttrList, string.format('shadow_offset="%s"', Style.shadow_offset))
    end

    if #AttrList <= 0 then
        return RichText.EscapeText(Text)
    end

    return string.format("<font %s>%s</>", table.concat(AttrList, " "), RichText.EscapeText(Text))
end

function RichText.Image(Style)
    Style = Style or {}

    local AttrList = {}

    if Style.src then
        table.insert(AttrList, string.format('src="%s"', tostring(Style.src)))
    end

    if Style.size then
        table.insert(AttrList, string.format('size="%s"', tostring(Style.size)))
    elseif Style.width and Style.height then
        table.insert(AttrList, string.format('size="%s;%s"', tostring(Style.width), tostring(Style.height)))
    end

    if Style.baseline then
        table.insert(AttrList, string.format('baseline="%s"', tostring(Style.baseline)))
    end

    if Style.color then
        table.insert(AttrList, string.format('color="%s"', tostring(Style.color)));
    end
    return string.format("<pic %s/>", table.concat(AttrList, " "))
end

function RichText.Link(Text, Style)
    Style = Style or {}

    local AttrList = {}

    if Style.src then
        table.insert(AttrList, string.format('src="%s"', Style.src))
    end

    if Style.size then
        table.insert(AttrList, string.format('size="%s"', tostring(Style.size)))
    end

    if Style.color then
        table.insert(AttrList, string.format('color="%s"', tostring(Style.color)))
    end

    if Style.under_line then
        table.insert(AttrList, string.format('under_line="%s"', tostring(Style.under_line)))
    end

    if Style.flag then
        table.insert(AttrList, string.format('flag="%s"', tostring(Style.flag)))
    end
    if Style.lock then
        table.insert(AttrList, string.format('lock="%s"', tostring(Style.lock)))
    end
    if #AttrList <= 0 then
        return RichText.EscapeText(Text)
    end

    return string.format("<a2 %s>%s</>", table.concat(AttrList, " "), RichText.EscapeText(Text))
end

function RichText.Inline(...)
    local Result = {}

    for _, Text in ipairs({ ... }) do
        table.insert(Result, tostring(Text or ""))
    end

    return table.concat(Result, "")
end

function RichText.Line(...)
    local Result = {}
    for _, Text in ipairs({ ... }) do
        table.insert(Result, tostring(Text or ""))
    end

    return table.concat(Result, "\n")
end