---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dluckdu.
--- DateTime: 2024/11/18 16:56
---

---@type Delegate
local Delegate = require("common.Delegate")


---大厅通用的玩法逻辑事件都在这里定义，可自行选择需要的事件进行绑定。
---@class LobbyEvent
LobbyEvent = {
    ---@field OnLobbyFlowSwitchBefore fun(From:LobbyState, To:LobbyState)
    OnLobbyFlowSwitchBefore = Delegate.New(),
    ---@field OnLobbyFlowSwitchAfter fun(From:LobbyState, To:LobbyState)
    OnLobbyFlowSwitchAfter = Delegate.New(),
    ---@field OnModeSelected fun(ModeID:int32)
    OnModeSelected = Delegate.New(),
    ---@field OnDifficultySelected fun(Difficulty:string)
    OnDifficultySelected = Delegate.New(),
    ---@field OnLobbyExited fun()
    OnLobbyExited = Delegate.New(),
    ---@field OnStartMatch fun(bSucceed:bool)
    OnMatchStarted = Delegate.New(),
    ---@field OnMatchCanceled fun()
    OnMatchCanceled = Delegate.New(),
    ---@field OnMatchSuccess fun()
    OnMatchSuccess = Delegate.New(),
}