---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dluckdu.
--- DateTime: 2024/11/15 14:52
---


---@class FCombinedModeConfig
---@field ModeID int32
---@field DetailID int32
---@field ModeName FText
---@field ModeDesc FText
---@field ModeBanner UTexture2D
---@field ModePost UTexture2D
---@field Difficulty FText
---@field UnlockDesc FText


---@class LobbyModel
---@field GameModeConfigList FModeConfig[]
---@field GameModeDetailList FModeDetail[]
---@field CombinedModeConfigList FCombinedModeConfig[] @合并两张模式表后供大厅使用
LobbyModel = {
    -- 多模式匹配信息表，参考 .ugcproj 文件 [MultiModeSetting_X] 小节
    MultiModeConfigTableList = {},
    GameModeConfigList = {},
    GameModeDetailList = {},
    CombinedModeConfigList = {},
    CurrentSelectedModeID = -1,
    bIsMatching = false,
}


---初始化，在大厅启动时调用，否则所有 Model 逻辑不可用
function LobbyModel:Init()
    ugcprint("[LobbyModel:Init]")
    self.MultiModeConfigTableList = {}

    -- 读项目工程里的模式配置表
    local MultiModeConfigList = GameFrontendHUD:UGCGetMultiModeConfig()
    local MultiModeNum = MultiModeConfigList:Num()

    if MultiModeNum <= 0 then return end

    for i = 1, MultiModeNum, 1 do
        local MultiModeConfigJsonString = MultiModeConfigList:Get(i)
        local MultiModeConfigTable = json.decode(MultiModeConfigJsonString)
        if MultiModeConfigTable.ModeID ~= "1001" then
            table.insert(self.MultiModeConfigTableList, MultiModeConfigTable)
        end
    end

    -- 读 GameModeConfigTable
    local GameModeConfigTablePath = UGCGameSystem.GetUGCResourcesFullPath('Asset/Data/Table/UGCGameModeConfig.UGCGameModeConfig')
    local GameModeConfigTable = UGCGameSystem.GetTableData(GameModeConfigTablePath)
    for _, GameModeConfigRow in pairs(GameModeConfigTable) do
        table.insert(self.GameModeConfigList, GameModeConfigRow)
    end

    -- 读 GameModeDetailTable
    local GameModeDetailTablePath = UGCGameSystem.GetUGCResourcesFullPath('Asset/Data/Table/UGCGameModeDetail.UGCGameModeDetail')
    local GameModeDetailTable = UGCGameSystem.GetTableData(GameModeDetailTablePath)
    for _, GameModeDetailRow in pairs(GameModeDetailTable) do
        table.insert(self.GameModeDetailList, GameModeDetailRow)
    end

    -- 合并两张表
    self:CombineModeConfigTable()

    -- 默认选择第一个模式、简单难度
    local DefaultModeID = self:IsModeIDValid(self.CurrentSelectedModeID) and self.CurrentSelectedModeID or self:GetAllModeID()[1]
    self:SelectMode(DefaultModeID, true)

    -- 注册匹配事件
    UGCMultiMode.NotifyMatchResponseDelegate:Add(self.OnMatchStarted, self)
    UGCMultiMode.NotifyMatchSucceededDelegate:Add(self.OnMatchSuccess, self)

end

---获取所有模式配置
---@param DetailID int32
---@return FCombinedModeConfig[]
function LobbyModel:GetAllModeConfig(DetailID)
    if DetailID == nil then
        return self.CombinedModeConfigList
    end

    local OutModeConfigs = {}
    for _, CombinedModeConfig in pairs(self.CombinedModeConfigList) do
        if CombinedModeConfig.DetailID == DetailID then
            table.insert(OutModeConfigs, CombinedModeConfig)
        end
    end

    return OutModeConfigs
end

---获取所有展示模式
function LobbyModel:GetAllDisplayModeID()
    local ModeMap = {}
    for _, CombinedModeConfig in pairs(self.CombinedModeConfigList) do
        if not ModeMap[CombinedModeConfig.DetailID] and not CombinedModeConfig.Hide then
            ModeMap[CombinedModeConfig.DetailID] = CombinedModeConfig.ModeID
        end
    end
    
    local UniqueModeIDListByDetail = {}
    for _, V in pairs(ModeMap) do
        table.insert(UniqueModeIDListByDetail, V)
    end

    table.sort(UniqueModeIDListByDetail, function(a, b)
        return self:GetModeConfig(a).DetailID < self:GetModeConfig(b).DetailID
    end)

    return UniqueModeIDListByDetail
end

---获取指定多模式配置表
---@param ModeID int32
---@return FCombinedModeConfig
function LobbyModel:GetModeConfig(ModeID)
    for _, CombinedModeConfig in pairs(self.CombinedModeConfigList) do
        if CombinedModeConfig.ModeID == ModeID then
            return CombinedModeConfig
        end
    end

    return nil
end

---获取当前选中的多模式配置表
---@return int32
function LobbyModel:GetCurrentSelectedModeID()
    return self.CurrentSelectedModeID
end

---获取当前选中的模式配置
function LobbyModel:GetCurrentSelectedMode()
    return self:GetModeConfig(self.CurrentSelectedModeID)
end

---获取所有模式 ID，已去除大厅
function LobbyModel:GetAllModeID()
    local ModeIDList = {}

    for _, GameModeConfig in pairs(self.CombinedModeConfigList) do
        if GameModeConfig.ModeID ~= 1001 then
            table.insert(ModeIDList, tonumber(GameModeConfig.ModeID))
        end
    end

    -- 对 ModeID 列表去重
    local UniqueModeIDList = {}
    local Seen = {}
    for _, modeID in ipairs(ModeIDList) do
        if not Seen[modeID] then
            Seen[modeID] = true
            table.insert(UniqueModeIDList, modeID)
        end
    end

    return UniqueModeIDList
end

---获取某个模式的难度列表
---@param ModeID int32 @可选，模式 ID
---@return FCombinedModeConfig[]
function LobbyModel:GetModeListWithSameDetailID(ModeID)
    if ModeID == nil then
        ModeID = self:GetCurrentSelectedModeID()
    end

    local ModeConfig = self:GetModeConfig(ModeID)
    local Result = {}
    for _, CombinedModeConfig in pairs(self.CombinedModeConfigList) do
        if CombinedModeConfig.DetailID == ModeConfig.DetailID then
            table.insert(Result, CombinedModeConfig)
        end
    end
    return Result
end

---获取当前已选难度
---@return string
function LobbyModel:GetCurrentSelectedDifficulty()
    local ModeID = self:GetCurrentSelectedModeID()
    local ModeConfig = self:GetModeConfig(ModeID)

    if ModeConfig then
        return ModeConfig.Difficulty
    end

    return ""
end

function LobbyModel:IsModeLocked(ModeID)
    local TargetModeID = ModeID or self:GetCurrentSelectedModeID()

    local PlayerState = UGCGameSystem.GetLocalPlayerState()
    local GameCompletionRecord = PlayerState.GameCompletionRecord or {}

    print("[LobbyModel:IsModeLocked]:初始游戏完成记录:")
    log_tree(GameCompletionRecord)

    for _, ID in pairs(GameCompletionRecord) do
        if tostring(ID) == tostring(TargetModeID) then
            return false
        end
    end

    return true
end

---检查模式 ID 是否有效
---@param ModeID number
---@return boolean
function LobbyModel:IsModeIDValid(ModeID)
    if ModeID == nil then return false end

    local bFindInMultiModeConfig = false
    local bFindInGameModeConfig = false

    for i = 1, #self.MultiModeConfigTableList, 1 do
        local MultiModeConfigTable = self.MultiModeConfigTableList[i]
        if MultiModeConfigTable.ModeID == tostring(ModeID) then
            bFindInMultiModeConfig = true
            break
        end
    end

    for i = 1, #self.CombinedModeConfigList, 1 do
        local CombinedModeConfig = self.CombinedModeConfigList[i]
        if CombinedModeConfig.ModeID == ModeID then
            bFindInGameModeConfig = true
            break
        end
    end

    if not bFindInMultiModeConfig then
        ugcprint("[LobbyModel:IsModeIDValid] Not found in MultiModeConfigTableList: " .. ModeID)
        return false
    end

    if not bFindInGameModeConfig then
        ugcprint("[LobbyModel:IsModeIDValid] Not found in ModeConfigList: " .. ModeID)
        return false
    end

    return true
end

---选择模式
---@param ModeID number
function LobbyModel:SelectMode(ModeID, bClientInit)
    bClientInit = bClientInit or false

    if self.bIsMatching then
        UGCWidgetManagerSystem.ShowTipsUI("匹配中无法选择模式")
        return
    end

    if self:IsModeIDValid(ModeID) then
        ugcprint("[LobbyEvent.OnModeSelected]" .. ModeID)
        self.CurrentSelectedModeID = ModeID

        LobbyEvent.OnModeSelected(ModeID)

        LobbyUtils.UpdateWidget(LobbyWidgetType.LWT_MainLobby, { ModeID = ModeID })

        local PC = UGCGameSystem.GetLocalPlayerController()
        -- if PC and PC.bIsTeamLeader and UGCGameSystem.GameState and not bClientInit then
        --     UnrealNetwork.CallUnrealRPC(PC, PC, "RPC_Server_SetLobbySelectedModeID", ModeID)
        -- end
    end
end

---选择难度
---@param Difficulty string
function LobbyModel:SelectDifficulty(Difficulty)
    ugcprint("[LobbyEvent.OnDifficultySelected]" .. Difficulty)
    LobbyEvent.OnDifficultySelected(Difficulty)

    local AllModeConfig = self:GetAllModeConfig(self:GetCurrentSelectedMode().DetailID)
    for _, ModeConfig in pairs(AllModeConfig) do
        if ModeConfig.Difficulty == Difficulty then
            self:SelectMode(ModeConfig.ModeID)
        end
    end

    LobbyUtils.UpdateWidget(LobbyWidgetType.LWT_MainLobby, { Difficulty = Difficulty })
    LobbyUtils.UpdateWidget(LobbyWidgetType.LWT_ModeSelect, { Difficulty = Difficulty })
end

---开始匹配
function LobbyModel:RequestMatch(bFillTeammate)
    if self.bIsMatching then
        UGCWidgetManagerSystem.ShowTipsUI("已经在匹配了")
        return
    end

    UGCMultiMode.RequestMatch(1002, nil, nil, true)
end

---取消匹配
function LobbyModel:CancelMatch()
    if UGCMultiMode.RequestCancelMatch() then
        self:OnMatchCanceled()
    else
        UGCWidgetManagerSystem.ShowTipsUI("取消匹配失败")
    end
end

function LobbyModel:IsMatching()
    return self.bIsMatching
end

function LobbyModel:ExitLobby()
    ugcprint("[LobbyEvent.OnLobbyExited]")
    LobbyEvent.OnLobbyExited()

    self:DoExitLobby()
end


---@private
function LobbyModel:OnMatchStarted(bSucceeded)
    if self:IsMatching() then
        ugcprint("[LobbyModel:OnMatchStarted] already matching")
        return
    end

    local PC = UGCGameSystem.GetLocalPlayerController()
    if not PC.bIsTeamLeader then
        return
    end

    self.bIsMatching = bSucceeded
    LobbyUtils.UpdateWidget(LobbyWidgetType.LWT_MainLobby, { bIsMatching = self.bIsMatching })
    UGCWidgetManagerSystem.ShowTipsUI("匹配" .. (bSucceeded and "开始" or "失败"))
    -- UnrealNetwork.CallUnrealRPC(PC, PC, "RPC_Server_SetLobbybIsMatching", bSucceeded)

    ugcprint("[LobbyEvent.OnStartMatch] bSucceeded = " .. tostring(bSucceeded))
    LobbyEvent.OnMatchStarted(bSucceeded)
end

---@private
function LobbyModel:OnMatchCanceled()
    ugcprint("[LobbyEvent.OnMatchCanceled]")

    local PC = UGCGameSystem.GetLocalPlayerController()
    if not PC.bIsTeamLeader then
        return
    end

    self.bIsMatching = false
    LobbyUtils.UpdateWidget(LobbyWidgetType.LWT_MainLobby, { bIsMatching = self.bIsMatching })

    -- UnrealNetwork.CallUnrealRPC(PC, PC, "RPC_Server_SetLobbybIsMatching", false)

    UGCWidgetManagerSystem.ShowTipsUI("匹配取消")
    LobbyEvent.OnMatchCanceled()
end

---@private
function LobbyModel:OnMatchSuccess()
    ugcprint("[LobbyEvent.OnMatchSuccess]")
    LobbyEvent.OnMatchSuccess()
end

---@private
function LobbyModel:DoExitLobby()
    UGCGameSystem.ReturnToLobby()
    UGCGameSystem.GameState:DestroyBattleWidget()
end

---@private
function LobbyModel:CombineModeConfigTable()
    self.CombinedModeConfigList = {}

    for _, ModeDetail in pairs(self.GameModeDetailList) do
        for _, ModeID in pairs(ModeDetail.ModeIDs) do
            for _, ModeConfig in pairs(self.GameModeConfigList) do
                if ModeID == ModeConfig.ModeID then
                    ---@type FCombinedModeConfig
                    local CombinedModeConfig = {}

                    CombinedModeConfig.ModeID = ModeID
                    CombinedModeConfig.DetailID = ModeDetail.ID
                    CombinedModeConfig.ModeName = ModeDetail.ModeName
                    CombinedModeConfig.ModeDesc = ModeDetail.ModeDesc
                    CombinedModeConfig.ModeBanner = ModeDetail.ModeBanner
                    CombinedModeConfig.ModePost = ModeDetail.ModePost
                    CombinedModeConfig.Difficulty = ModeConfig.Difficulty
                    CombinedModeConfig.UnlockDesc = ModeConfig.UnlockDesc
                    CombinedModeConfig.Hide = ModeDetail.Hide

                    table.insert(self.CombinedModeConfigList, CombinedModeConfig)
                end
            end
        end
    end
end