---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dluckdu.
--- DateTime: 2024/11/14 20:36
---

---@class LobbyWidgetType
LobbyWidgetType = {
    LWT_MainLobby = {
        Name = "MainLobby",
        Path = 'Asset/Blueprint/Prefabs/UI/Lobby/Home/HomeMain.HomeMain_C',
        Instance = nil,
    },
    LWT_ModeSelect = {
        Name = "ModeSelect",
        Path = 'Asset/Blueprint/Prefabs/UI/Lobby/Mode/UGC_ModeSelection_UIBP.UGC_ModeSelection_UIBP_C',
        Instance = nil,
    },
    LWT_ClosePopupsTips = {
        Name = "LWT_ClosePopupsTips",
        Path = 'Asset/Blueprint/Prefabs/UI/Lobby/UGC_ClosePopupsTips_UIBP.UGC_ClosePopupsTips_UIBP_C',
        Instance = nil
    },
    LWT_ModeDifficultyTip = {
        Name = "LWT_ModeDifficultyTip",
        Path = 'Asset/Blueprint/Prefabs/UI/Lobby/Mode/UGC_DifficultyTips_UIBP.UGC_DifficultyTips_UIBP_C',
        Instance = nil
    },
    LWT_RaidInstance = {
        Name = "RaidInstance",
        Path = 'Asset/Blueprint/Prefabs/UI/RaidInstance/RaidInstanceMain.RaidInstanceMain_C',
        Instance = nil,
    }
}


---@class LobbyUtils
LobbyUtils = LobbyUtils or {}


function LobbyUtils.GetWidget(WidgetType)
    -- lookup LobbyWidgetType in WidgetType
    if WidgetType and WidgetType.Name then
        for _, v in pairs(LobbyWidgetType) do
            if v == WidgetType then
                if WidgetType.Instance then
                    return WidgetType.Instance
                else
                    if not UGCGameSystem.GameState then return end

                    local FullPath = UGCGameSystem.GetUGCResourcesFullPath(WidgetType.Path)
                    local LobbyMainUIClass = UGCObjectUtility.LoadClass(FullPath)
                    local PlayerController = UGCGameSystem.GetLocalPlayerController()

                    if not LobbyMainUIClass or not PlayerController then return end

                    WidgetType.Instance = UserWidget.NewWidgetObjectBP(PlayerController, LobbyMainUIClass)
                    WidgetType.Instance:AddToViewport()
                    WidgetType.Instance:SetVisibility(ESlateVisibility.Collapsed)
                    return WidgetType.Instance
                end
            end
        end
    end
end

function LobbyUtils.OpenWidget(WidgetType, ...)
    local Widget = LobbyUtils.GetWidget(WidgetType)

    if Widget.bIsOpened then return end

    Widget:SetVisibility(ESlateVisibility.SelfHitTestInvisible)

    if Widget.OnOpen then
        Widget:OnOpen(select("#", ...) > 0 and ... or {})
    end

    Widget.bIsOpened = true
end

function LobbyUtils.CloseWidget(WidgetType)
    local Widget = LobbyUtils.GetWidget(WidgetType)

    if not Widget.bIsOpened then return end

    -- Widget:RemoveFromViewport()
    Widget:SetVisibility(ESlateVisibility.Collapsed)

    if Widget.OnClose then
        Widget:OnClose()
    end

    Widget.bIsOpened = false
end

function LobbyUtils.UpdateWidget(WidgetType, ...)
    local Widget = LobbyUtils.GetWidget(WidgetType)
    if Widget == nil then
        return
    end

    if not Widget.bIsOpened then return end

    if Widget.OnUpdate then
        ugcprint("[LobbyUtils] UpdateWidget: " .. WidgetType.Name)
        Widget:OnUpdate(select("#", ...) > 0 and ... or {})
    end
end

function LobbyUtils.OpenAndUpdateWidget(WidgetType, ...)
    LobbyUtils.OpenWidget(WidgetType, ...)
    LobbyUtils.UpdateWidget(WidgetType, ...)
end

function LobbyUtils.SetOtherWidgetHidden(bHidden)
    
end

function LobbyUtils.GetTrimmedString(InStr, Max)
    local OutStr = InStr
    local Count = FuncUtil.GetStringLength(OutStr)

    if Count > Max then
        OutStr = FuncUtil.SubString(OutStr, 1, Max) .. "..."
    end
    return OutStr or ""
end