---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dluckdu.
--- DateTime: 2024/11/14 20:01
---

UGCGameSystem.UGCRequire("Script.Blueprint.Prefabs.UI.Lobby.LobbyUtils")
UGCGameSystem.UGCRequire("Script.Blueprint.Prefabs.UI.Lobby.LobbyModel")
UGCGameSystem.UGCRequire("Script.Blueprint.Prefabs.UI.Lobby.LobbyEvent")


---@class LobbyFlow
local LobbyFlow = {}


---@type LobbyStateSwitcher
local LobbyStateSwitcher = UGCGameSystem.UGCRequire("Script.Blueprint.Prefabs.UI.Lobby.LobbyState")


---@class LobbyFlowImpl
local _LobbyFlowImpl = {
    CurrentState = LobbyFlowState.LFS_None,
}


--[[----------------------------------------------------- API ------------------------------------------------------]]--

---检查是否可以进入状态
---可省略 To，检查是否可以从当前状态跳转到指定状态
---@param From LobbyState @切换前状态
---@param To LobbyState @切换后状态
---@return bool @切换条件是否可用
function LobbyFlow:CanGO(From, To)
    return _LobbyFlowImpl:CanGO(From, To)
end

---进入另一状态
---@param To LobbyState @要前往的状态
function LobbyFlow:Go(To)
    return _LobbyFlowImpl:Go(To)
end

---获取当前状态
---@return LobbyState @当前状态
function LobbyFlow:CurrentState()
    return _LobbyFlowImpl.CurrentState
end

--[[----------------------------------------------------- API ------------------------------------------------------]]--


function _LobbyFlowImpl:CanGO(From, To)
    -- 服务器不执行 UI 逻辑
    if UGCGameSystem.IsServer() then return false end
    return LobbyStateSwitcher:CanSwitch(From, To)
end

function _LobbyFlowImpl:Go(To)
    -- 服务器不执行 UI 逻辑
    if UGCGameSystem.IsServer() then return end

    ugcprint("[LobbyFlow] Go: " .. To)

    local From = self.CurrentState

    if not self:CanGO(From, To) then
        ugcprint("[LobbyFlow] Can't switch state: " .. From .. " -> " .. To)
        return
    end

    ugcprint("[LobbyFlow] Begin switch state: " .. From .. " -> " .. To)

    LobbyEvent.OnLobbyFlowSwitchBefore(From, To)
    LobbyStateSwitcher:Switch(From, To)
    LobbyEvent.OnLobbyFlowSwitchAfter(From, To)

    ugcprint("[LobbyFlow] End switch state: " .. From .. " -> " .. To)

    self.CurrentState = To
end


return LobbyFlow